version: 0.0
os: windows
files:
  - source: \
    destination: C:\Users\Administrator\Downloads\Pkg
hooks:
  BeforeInstall:
  AfterInstall:
  ApplicationStart:
    - location: start.bat
      timeout: 300
      runas: Administrator
  ApplicationStop: