version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    build:
        commands:
            - dotnet --info
            - dotnet publish -c Release -r win10-x64
            - cp appspec.yml bin/Release/netcoreapp3.1
            - cp start.bat bin/Release/netcoreapp3.1/win10-x64
            - zip -r output.zip bin
            - pwd
            - ls
artifacts:
    base-directory: bin/Release/netcoreapp3.1/win10-x64
    files:
        - '**/*'
