version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    build:
        commands:
            - dotnet --info
            - dotnet build 
            - dotnet publish
            - cp appspec.yml bin/Debug/netcoreapp3.1
            - zip -r output.zip bin
            - pwd
            - ls
artifacts:
    base-directory: bin/Debug/netcoreapp3.1
    files:
        - '**/*'
