version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    build:
        commands:
            - dotnet --info
            - dotnet build 
            - dotnet publish
            - ls bin
artifacts:
    files:
        - bin/Debug
